# etd/db/db_setup.py

import sqlite3
from pathlib import Path

DATABASE_PATH = 'etd.db'

def init_db(db_path=DATABASE_PATH):
    """
    Initialize the database schema (create tables if they don't exist).
    
    Parameters:
    db_path (str): Path to the SQLite database file.
    """
    try:
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()

        # Create Genomes table
        cursor.execute('''CREATE TABLE IF NOT EXISTS genomes (
                          id INTEGER PRIMARY KEY,
                          genome_name TEXT NOT NULL,
                          organism TEXT NOT NULL)''')

        # Create Sketch table for storing the single sketch file
        cursor.execute('''CREATE TABLE IF NOT EXISTS sketch (
                          id INTEGER PRIMARY KEY,
                          sketch_path TEXT NOT NULL)''')

        # Create Annotations table
        cursor.execute('''CREATE TABLE IF NOT EXISTS annotations (
                          id INTEGER PRIMARY KEY,
                          genome_id INTEGER REFERENCES genomes(id),
                          gene_name TEXT,
                          amr_annotation TEXT,
                          amr_output_path TEXT,
                          plasmid_annotation TEXT,
                          plasmid_output_path TEXT,
                          integron_annotation TEXT,
                          integron_output_path TEXT
                          prophage_annotation TEXT,
                          prophage_output_path TEXT,
                          Transposon_annotation TEXT,
                          Transposon_annotation_path TEXT,
                          ICE_annotation TEXT,
                          ICE_annotation_path TEXT)''')

        conn.commit()
    except sqlite3.Error as e:
        print(f"Error initializing database: {e}")
        raise

def create_genome_entry(cursor, fasta_name, organism):
    """
    Create and store a Genome entry in the database, including the organism name.

    Parameters:
    cursor (sqlite3.Cursor): Database cursor object.
    fasta_name (str): The name of the FASTA file.
    organism (str): The name of the organism.

    Returns:
    int: The ID of the created genome entry.
    """
    try:
        cursor.execute("INSERT INTO genomes (genome_name, organism) VALUES (?, ?)", (fasta_name, organism))
        genome_id = cursor.lastrowid
        if genome_id is None:
            raise sqlite3.IntegrityError(f"Failed to insert genome '{fasta_name}'.")
        return genome_id
    except sqlite3.Error as e:
        print(f"Error inserting genome '{fasta_name}': {e}")
        raise

def store_sketch(sketch_path, cursor):
    """
    Store Mash sketch in the DB.

    Parameters:
    sketch_path (Path) : Path to the sketch file generated by upstream mash paste module
    cursor (sqlite3.Cursor): Database cursor object.
    """
    sketch_path = sketch_path.resolve()

    if not sketch_path.exists():
        raise FileNotFoundError(f"Sketch not found: {sketch_path}")

    if sketch_path.suffix != ".msh":
        print(f"Warning: expected .msh, got {sketch_path.suffix}: {sketch_path}")

    cursor.execute(
        "INSERT INTO sketch (sketch_path) VALUES (?) "
        "ON CONFLICT(sketch_path) DO NOTHING",
        (str(sketch_path),)
    )


def parse_amr_annotation(amrfinder_output, genome_id):
    """
    Read the AMRFinder output (TSV), pick columns by index, and return a list of dicts.

    Parameters:
    amrfinder_output (str): Path to the output file from upstream amrfinder module.
    genome_id (int): The ID of the genome entry.

    Returns:
    amr_annotations (list): A list of annotations where each annotation is a dictionary with keys 'genome_id', 'gene' and 'annotation'.
    

    """
    try:
        amr_annotations = []
        with open(amrfinder_output, "r") as f:
            # skip header
            next(f, None)
            for line in f:
                line = line.strip()
                if not line:
                    continue
                parts = line.split("\t")
                if len(parts) < 7:
                    # skip malformed/short lines
                    continue
                contig_id = parts[1]
                gene_name = parts[5]
                annotation = parts[6]
                amr_annotations.append({
                    "genome_id": genome_id,
                    "contig_id": contig_id,
                    "amr_gene": gene_name,
                    "annotation": annotation
                })
        return amr_annotations
    except Exception as e:
        print(f"An unexpected error occurred while parsing {amrfinder_output}: {e}")
        raise


def store_amr_annotation(amr_annotations, cursor, output_path):
    """
    Store AMR annotations in the database.

    Parameters:
    amr_annotations (list): list of amr_annotation dicts.
    output_path (str): Path to the output file from upstream amrfinder module.
    cursor (sqlite3.Cursor): Database cursor object..
    """
    
    try:
        for annotation in amr_annotations:
            cursor.execute(
                "INSERT INTO annotations (genome_id, gene_name, amr_annotation, amr_output_path) VALUES (?, ?, ?, ?)",
                (annotation['genome_id'], annotation['amr_gene'], annotation['annotation'], output_path))
    except sqlite3.Error as e:
        print(f"Error storing AMR annotations: {e}")
        raise

def parse_plasmid_annotation(contigs_report_path):
    """
    Read in the mob-suite contigs_report.txt and return a dict of plasmid annotations

    Parameters:
    contigs_report_path (str): Path to the output file from upstream mob-suite module

    Returns:
    plasmid annotations (dict): dict of plamid annotations.
    """
    try:
        plasmid_annotations = {}
        with open(contigs_report_path) as f:
            next(f, None)  # skip header
            for line in f:
                parts = line.strip().split("\t")
                if len(parts) < 5:
                    continue

                molecule_type_full = parts[1].strip()
                first_token = molecule_type_full.split(None, 1)[0].lower() if molecule_type_full else ""
                if first_token != "plasmid":
                    continue

                contig_id_norm = parts[4].split()[0]
                if not contig_id_norm:
                    continue

                plasmid_annotations[contig_id_norm] = {
                    "contig_id": contig_id_norm,
                    "plasmid": molecule_type_full
                }
        return plasmid_annotations
    except Exception as e:
        print(f"An unexpected error occurred while parsing {contigs_report_path}: {e}")
        raise

def merge_amar_plasmid_annotation(amr_annotations, plasmid_annotations):
    """
    Join AMR rows with plasmid annotations by contig_id.

    Returns:
        list of dicts: {
            "genome_id": ...,
            "amr_gene": ...,
            "plasmid_annotation": ...,
        }
    """
    amr_plasmid_annotations = []
    for annotation in amr_annotations:
        info = plasmid_annotations.get(annotation["contig_id"])
        if info:
            amr_plasmid_annotations.append({
                "genome_id": annotation["genome_id"],
                "gene": annotation["amr_gene"],
                "plasmid_annotation": info["plasmid"],
                "plasmid_id": info["contig_id"]
                })

    return amr_plasmid_annotations

def store_amr_plasmid_annotations(amr_plasmid_annotations, cursor):
    """
    Update existing AMR rows with plasmid info.

    amr_plasmid_annotations: list of dicts like:
      {"genome_id": int, "contig_id": str, "amr_gene": str, "plasmid_annotation": str}

    Returns:
      int: number of table rows updated.
    """
    total_updated = 0
    for row in amr_plasmid_annotations:
        genome_id = row.get("genome_id")
        contig_id = row.get("contig_id")
        gene      = row.get("amr_gene")
        plasmid   = row.get("plasmid_annotation")

        cursor.execute(
            """
            UPDATE annotations
                SET plasmid_annotation = ?
            WHERE genome_id = ?
                AND gene_name = ?
            """,
                (plasmid, genome_id, gene)
            )
        total_updated += cursor.rowcount
    return total_updated
