contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #etd channel"
    url: https://nfcore.slack.com/channels/etd
    about: Discussion about the nf-core/etd pipeline
